[박서윤] Mission 5: 회원가입 비밀번호 암호화 적용
wecode-bootcamp-korea/35-backend-westagram-2 pull request #22
Opened 2022-07-11 08:10 UTC by happy-tiger212

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 회원가입 비밀번호 암호화 적용
		 
## 수정 사항들 자세한 내용
- password를 hashed하여 hashed_password에 저장
- bytes 단위인 hashed_password를 decode 즉, string으로 변환하여 decoded_password에 저장
- 암호화된 decoded_password를 비밀번호로 저장

## 기타 질문 및 특이 사항
없음

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-07-11 08:27 UTC, kdylsky commented on students/seoyun/westagram/users/views.py
> +                password     = decoded_password,
아직 코드 구현 전이지만 동기분들의 코드를 보면서 오늘 배운 내용을 복습할 수 있는 시간이 된것 같아 

좋은 것 같습니다!!! 감사합니다..

2022-07-11 08:54 UTC, schk9611 commented on students/seoyun/westagram/users/views.py
>                  return JsonResponse({'message':'이미 가입된 이메일 입니다.'}, status=400)
이 사항은 SignUp을 구현할 때 고치시는 편이 더 좋을 것 같습니다!

2022-07-11 08:54 UTC, schk9611 commented on students/seoyun/westagram/users/views.py
> +            decoded_password = hashed_password.decode('utf-8')
알아보기 쉽게 잘 구현된 것 같습니다!

2022-07-12 02:56 UTC, bigfanoftim requested changes

2022-07-12 02:56 UTC, bigfanoftim commented on students/seoyun/westagram/users/views.py
> +            if User.objects.filter(email=email):
`exists()`를 지우신 이유가 무엇인가요?

2022-07-12 02:56 UTC, bigfanoftim commented on students/seoyun/westagram/users/views.py
> +            decoded_password = hashed_password.decode('utf-8')
```suggestion
            hashed_password  = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')
```
그렇게 복잡하지 않은 코드이고 굳이 활용되지 않을 변수를 지정할 필요는 없어 보이네요.
만약 가독성을 생각하신거라면 다음과 같이 다른 시도를 해보실 수 있습니다.
```suggestion
            hashed_password  = bcrypt.hashpw(
                password.encode('utf-8'), 
                bcrypt.gensalt()
            ).decode('utf-8')
```

2022-07-12 04:13 UTC, happy-tiger212 commented on students/seoyun/westagram/users/views.py
> +            if User.objects.filter(email=email):
filter의 조건에 해당하는 객체가 존재한다면 객체들이 쿼리셋에 담겨 반환되고, 존재하지 않는다면 빈 쿼리셋으로 반환된다고 알고 있습니다. 빈 쿼리셋이면 False로 취급이 되고, 쿼리셋에 객체가 존재하면 True로 취급되기에, exists()가 필요하지 않다고 판단했습니다!

2022-07-12 07:27 UTC, bigfanoftim requested changes

2022-07-12 07:27 UTC, bigfanoftim commented on students/seoyun/westagram/users/views.py
> +            if User.objects.filter(email=email):
<img width="510" alt="image" src="https://user-images.githubusercontent.com/62135254/178433226-c08f07f5-9cfb-45f2-a690-d7ddf0ec19e9.png">

말씀해주신 내용은 맞지만 사실 filter를 사용하게 되면 해당 조건에 맞는 모든 데이터를 다 불러오게 됩니다.
지금 상황에서는 true or false만 필요하기 때문에  exists()를 쓰는 것이 더 효율적으로 보입니다!

2022-07-12 07:55 UTC, happy-tiger212 commented on students/seoyun/westagram/users/views.py
> +            if User.objects.filter(email=email):
네 감사합니다! 수정완료했습니다!

2022-07-12 08:24 UTC, bigfanoftim approved these changes
LGTM 👍

2022-07-12 08:25 UTC, merged